# Generated by Django 4.1.6 on 2023-07-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_alter_location_latitude_alter_location_longitude"),
    ]

    operations = [
        migrations.CreateModel(
            name="FencedField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("point1", models.FloatField()),
                ("point2", models.FloatField()),
                ("point3", models.FloatField()),
                ("point4", models.FloatField()),
            ],
        ),
    ]
