# Generated by Django 4.1.6 on 2023-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0004_fencedfield_timestamp"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fencedfield",
            old_name="point1",
            new_name="point1lat",
        ),
        migrations.RenameField(
            model_name="fencedfield",
            old_name="point2",
            new_name="point1lon",
        ),
        migrations.RenameField(
            model_name="fencedfield",
            old_name="point3",
            new_name="point2lat",
        ),
        migrations.RenameField(
            model_name="fencedfield",
            old_name="point4",
            new_name="point2lon",
        ),
        migrations.AddField(
            model_name="fencedfield",
            name="point3lat",
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fencedfield",
            name="point3lon",
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fencedfield",
            name="point4lat",
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fencedfield",
            name="point4lon",
            field=models.FloatField(default=20),
            preserve_default=False,
        ),
    ]
